backend:
  name: github
  repo: heinekin/gatsby-style-guide-guide
  branch: netlify-cms

publish_mode: editorial_workflow

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "guidelines"
    label: "Guidelines"
    folder: "content/guidelines"
    create: true
    fields:
      - {label: "layout", name: "layout", widget: "string"}
      - {label: "type", name: "type", widget: "string"}
      - {label: "title", name: "title", widget: "string"}
      - {label: "group", name: "group", widget: "string"}
      - {label: "path", name: "path", widget: "string"}
      - {label: "status", name: "status", widget: "string"}
      - {label: "description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}